name: docker

on:
  push:
    branches: [ "pipeline_docker" ]

env:
  IMAGENAME: 'totvsengpro/tir'
  RELEASE_VERSION: '1.20.19'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Set release
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          push: true
          tags: ${{ env.IMAGENAME }}:${{ env.RELEASE_VERSION }},${{ env.IMAGENAME }}:latest